# Basic
title: 渚碧
author: Juby
url: https://jubeny.com
timezone: Asia/Shanghai
build_date: 2015/01/03 23:15:15

# SEO
keywords: [渚碧博客, Juby Blog, 读书·生活·运动, 自由民主]
description: 我欲种菜 亦植蔷薇

# Social
social:
  twitter: roadfar
  instagram: aggwr64
  youtube: lowah1964

# Disqus
disqus: 
  shortname: juby
  sitename: AoiNagisa
  apikey: dXc0vOCZ1LAX0c9y3FB0fpC5KA7L56QEFDYRXaUeAyvCzowv8hKQRzpsG6ITpxSL
  admin: mikihiro
  mod: Mod
  nocomment: Hello? Is there anybody in there?

# Google
# google: 
#   analytics: UA-112090731-1
#   site_verification: lTL7MkDxY16gNmRWyqoZYflJgECNQkxPjyFoYgM3z2M

# Clicky site id
# clicky: 101359865

# Follow RSS
follow:
  feed_id: 41343619752158229
  user_id: 67699324184418304

# Open Graph & Twitter Card
card: https://bing.ee123.net/img/

# cdn server
cdn: fastly.jsdelivr.net

# Cloudinary
cloudinary: https://res.cloudinary.com/dajdhi0qn/image/upload/f_auto

# Algolia search
algolia:
  application_id: XTX1EOVMI5
  index_name: jubeny
  search_only_api_key: d57fd011fd186e67019b3e2ad08c5ec2

# Algolia Crawler Netlify
crawler:
  appId: G6EJRG4B61
  apiKey: 08c77760bc896f05c67bbb210d844028
  siteId: 2892d0db-3067-4a2f-907d-d8e43bedb5c1

# Navigation buttons
nav:
  - {title: 首页, description: blog, url: '/'}
  - {title: 往事, description: archive, url: '/archive/'}   
  - {title: 读书, description: book, url: '/book/'}
  - {title: 留言, description: guestbook, url: '/guestbook/'}      
  - {title: 关于, description: about, url: '/about/'}         

# Categories
categs:
  - {title: J, description: 日志, url: '/journal/'}
  - {title: E, description: 随笔,url: '/essay/'}
  - {title: R, description: 评论,url: '/review/'}
  - {title: P, description: 诗歌,url: '/poetry/'}
  - {title: S, description: 故事,url: '/story/'}


# -------------------------Personal Setting Above-------------------------
# 
#          jekyll docs: https://jekyllrb.com/docs/
#
# --------------------------Jekyll Setting Below--------------------------


# Permalink
permalink: '/:year/:month/:title/'

# Format
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins: 
  - jekyll-paginate-v2
  - jekyll-sitemap
  # - jekyll-algolia

# Pagination
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# autopage_tags
autopages:
  enabled: true
  categories: 
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    layouts: 
      - 'autopage_tags.html'
    title: '标签 - :tag'
    permalink: '/tags/:tag'

# Increase jekyll build speed
exclude: [Gemfile, Gemfile.lock, README.md]
keep_files: [images]
incremental: false

# Redirect
include: [_redirects]