#
###################################
# Site wide configuration
####################################
#
title:       "Scott's Blog | 一生想做优雅前端"
description: "Chengfeilong's Blog. A front-end web developer who loves design awesome things. Working for Kingdee in Shenzhen, China."
keywords: "成飞龙、成启、chengfeilong、wangpengfei15975、Scott's Blog、Front-End Engineer"
url: http://www.chengfeilong.com # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shenzhen
markdown:          kramdown
highlighter:       pygments
excerpt_separator: <!--more-->
permalink:         /:title
paginate:          7
paginate_path:     "page:num"
gems:              [jekyll-paginate]

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Sass
####################################
#
sass:
  style: compressed

#
###################################
# loading
####################################
#
loading: "http://www.chengfeilong.com/img/loading.gif"

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Scott
  avatar: avatar.jpg
  job: "front-end developer"
  bio: "一生想做优雅前端."
  email: me@chengfeilong.com
  disqus-shortname: Sco7777777 #username
  duoshuo-shortname: chengfeilong #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: #UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: wangpengfei15975 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: Sco7777777 #username
  flickr: #username
  codepen: #username
  zhihu: #se7en-zone username
